// lib/main.dart
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:nyota/firebase_options.dart'; // ← correct import (generated by flutterfire)
import 'package:nyota/theme.dart';

// Import your screens
import 'screens/landing_screen.dart';
import 'screens/login_screen.dart';
import 'screens/signup_screen.dart';
import 'screens/maindashboard_screen.dart';
import 'screens/parentdashboard_screen.dart'; // Parent dashboard

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase BEFORE runApp
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const NyotaApp());
}

class NyotaApp extends StatelessWidget {
  const NyotaApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Nyota - Learning Adventure',
      debugShowCheckedModeBanner: false,

      theme: ThemeData(
        primaryColor: AppTheme.primary,
        scaffoldBackgroundColor: AppTheme.background,
        textTheme: GoogleFonts.fredokaTextTheme(
          Theme.of(context).textTheme.apply(
            bodyColor: AppTheme.textPrimary,
            displayColor: AppTheme.textPrimary,
          ),
        ),
        colorScheme: ColorScheme.fromSeed(
          seedColor: AppTheme.primary,
          brightness: Brightness.light,
        ),
        useMaterial3: true,
      ),

      // Initial route
      home: const LandingPage(),

      // Named routes
      routes: {
        '/login': (context) => const NyotaLoginPage(),
        '/signup': (context) => const SignupScreen(),
        '/main-dashboard': (context) => const MainDashboardScreen(),
        '/parent-dashboard': (context) => const ParentDashboard(),
      },
    );
  }
}

// Optional: Auth wrapper (recommended for protecting routes)
// You can wrap the whole app or just the dashboard later
class AuthWrapper extends StatelessWidget {
  const AuthWrapper({super.key});

  @override
  Widget build(BuildContext context) {
    return StreamBuilder<User?>(
      stream: FirebaseAuth.instance.authStateChanges(),
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const Scaffold(body: Center(child: CircularProgressIndicator()));
        }

        // If user is logged in, go to dashboard; else login
        if (snapshot.hasData) {
          return const MainDashboardScreen();
        }
        return const NyotaLoginPage();
      },
    );
  }
}
